# Build stage
FROM node:20-alpine AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
# Replace [APP_NAME] with the actual app name or use an argument
ARG APP_NAME
RUN pnpm turbo run build --filter=$APP_NAME

# Production stage (Static assets)
FROM nginx:alpine
ARG APP_NAME
ARG BUILD_OUTPUT_DIR=dist
COPY --from=builder /app/apps/$APP_NAME/$BUILD_OUTPUT_DIR /usr/share/nginx/html
# Copy custom nginx config for CORS support
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
