name: Reusable Deploy Vercel

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'App name'
      vercel_has_secrets:
        required: true
        type: boolean
      vercel_has_project_id:
        required: true
        type: boolean
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: false

jobs:
  deploy:
    name: Deploy ${{ inputs.app }} to Vercel
    runs-on: ubuntu-latest
    if: ${{ inputs.vercel_has_secrets && inputs.vercel_has_project_id }}
    steps:
      - uses: actions/checkout@v4

      - name: Download ${{ inputs.app }} build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.app }}-build
          path: apps/${{ inputs.app }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/${{ inputs.app }}
          vercel-args: ${{ inputs.app == 'shell' && '--prod' || '--prebuilt --prod' }}
